#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -I.sfml/include
CFLAGS = -Wall
RESINC = 
LIBDIR = -L.sfml/lib -L../fmq-cppgame
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC) -Isrc/entities/texture -Isrc/engine/state/menu-state -Isrc/engine/state -Isrc/engine/movement
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)-l.sfml/lib/libsfml-audio.so -l.sfml/lib/libsfml-graphics.so -l.sfml/lib/libsfml-network.so -l.sfml/lib/libsfml-system.so -l.sfml/lib/libsfml-window.so
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/fmq-cppgame

INC_RELEASE = $(INC) -Isrc/entities/texture -Isrc/engine/state/menu-state -Isrc/engine/state -Isrc/engine/movement
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)-l.sfml/lib/libsfml-audio.so -l.sfml/lib/libsfml-graphics.so -l.sfml/lib/libsfml-network.so -l.sfml/lib/libsfml-system.so -l.sfml/lib/libsfml-window.so
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/fmq-cppgame

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/engine/game/game.o $(OBJDIR_DEBUG)/src/engine/movement/movementcomponent.o $(OBJDIR_DEBUG)/src/engine/state/gamestate.o $(OBJDIR_DEBUG)/src/entities/circle/circle.o $(OBJDIR_DEBUG)/src/entities/entity.o $(OBJDIR_DEBUG)/src/entities/rectangle/rectangle.o $(OBJDIR_DEBUG)/src/main.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/engine/game/game.o $(OBJDIR_RELEASE)/src/engine/movement/movementcomponent.o $(OBJDIR_RELEASE)/src/engine/state/gamestate.o $(OBJDIR_RELEASE)/src/entities/circle/circle.o $(OBJDIR_RELEASE)/src/entities/entity.o $(OBJDIR_RELEASE)/src/entities/rectangle/rectangle.o $(OBJDIR_RELEASE)/src/main.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src/engine/game || mkdir -p $(OBJDIR_DEBUG)/src/engine/game
	test -d $(OBJDIR_DEBUG)/src/engine/movement || mkdir -p $(OBJDIR_DEBUG)/src/engine/movement
	test -d $(OBJDIR_DEBUG)/src/engine/state || mkdir -p $(OBJDIR_DEBUG)/src/engine/state
	test -d $(OBJDIR_DEBUG)/src/entities/circle || mkdir -p $(OBJDIR_DEBUG)/src/entities/circle
	test -d $(OBJDIR_DEBUG)/src/entities || mkdir -p $(OBJDIR_DEBUG)/src/entities
	test -d $(OBJDIR_DEBUG)/src/entities/rectangle || mkdir -p $(OBJDIR_DEBUG)/src/entities/rectangle
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/engine/game/game.o: src/engine/game/game.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/engine/game/game.cpp -o $(OBJDIR_DEBUG)/src/engine/game/game.o

$(OBJDIR_DEBUG)/src/engine/movement/movementcomponent.o: src/engine/movement/movementcomponent.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/engine/movement/movementcomponent.cpp -o $(OBJDIR_DEBUG)/src/engine/movement/movementcomponent.o

$(OBJDIR_DEBUG)/src/engine/state/gamestate.o: src/engine/state/gamestate.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/engine/state/gamestate.cpp -o $(OBJDIR_DEBUG)/src/engine/state/gamestate.o

$(OBJDIR_DEBUG)/src/entities/circle/circle.o: src/entities/circle/circle.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/entities/circle/circle.cpp -o $(OBJDIR_DEBUG)/src/entities/circle/circle.o

$(OBJDIR_DEBUG)/src/entities/entity.o: src/entities/entity.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/entities/entity.cpp -o $(OBJDIR_DEBUG)/src/entities/entity.o

$(OBJDIR_DEBUG)/src/entities/rectangle/rectangle.o: src/entities/rectangle/rectangle.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/entities/rectangle/rectangle.cpp -o $(OBJDIR_DEBUG)/src/entities/rectangle/rectangle.o

$(OBJDIR_DEBUG)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.cpp -o $(OBJDIR_DEBUG)/src/main.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src/engine/game
	rm -rf $(OBJDIR_DEBUG)/src/engine/movement
	rm -rf $(OBJDIR_DEBUG)/src/engine/state
	rm -rf $(OBJDIR_DEBUG)/src/entities/circle
	rm -rf $(OBJDIR_DEBUG)/src/entities
	rm -rf $(OBJDIR_DEBUG)/src/entities/rectangle
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src/engine/game || mkdir -p $(OBJDIR_RELEASE)/src/engine/game
	test -d $(OBJDIR_RELEASE)/src/engine/movement || mkdir -p $(OBJDIR_RELEASE)/src/engine/movement
	test -d $(OBJDIR_RELEASE)/src/engine/state || mkdir -p $(OBJDIR_RELEASE)/src/engine/state
	test -d $(OBJDIR_RELEASE)/src/entities/circle || mkdir -p $(OBJDIR_RELEASE)/src/entities/circle
	test -d $(OBJDIR_RELEASE)/src/entities || mkdir -p $(OBJDIR_RELEASE)/src/entities
	test -d $(OBJDIR_RELEASE)/src/entities/rectangle || mkdir -p $(OBJDIR_RELEASE)/src/entities/rectangle
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/engine/game/game.o: src/engine/game/game.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/engine/game/game.cpp -o $(OBJDIR_RELEASE)/src/engine/game/game.o

$(OBJDIR_RELEASE)/src/engine/movement/movementcomponent.o: src/engine/movement/movementcomponent.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/engine/movement/movementcomponent.cpp -o $(OBJDIR_RELEASE)/src/engine/movement/movementcomponent.o

$(OBJDIR_RELEASE)/src/engine/state/gamestate.o: src/engine/state/gamestate.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/engine/state/gamestate.cpp -o $(OBJDIR_RELEASE)/src/engine/state/gamestate.o

$(OBJDIR_RELEASE)/src/entities/circle/circle.o: src/entities/circle/circle.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/entities/circle/circle.cpp -o $(OBJDIR_RELEASE)/src/entities/circle/circle.o

$(OBJDIR_RELEASE)/src/entities/entity.o: src/entities/entity.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/entities/entity.cpp -o $(OBJDIR_RELEASE)/src/entities/entity.o

$(OBJDIR_RELEASE)/src/entities/rectangle/rectangle.o: src/entities/rectangle/rectangle.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/entities/rectangle/rectangle.cpp -o $(OBJDIR_RELEASE)/src/entities/rectangle/rectangle.o

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src/engine/game
	rm -rf $(OBJDIR_RELEASE)/src/engine/movement
	rm -rf $(OBJDIR_RELEASE)/src/engine/state
	rm -rf $(OBJDIR_RELEASE)/src/entities/circle
	rm -rf $(OBJDIR_RELEASE)/src/entities
	rm -rf $(OBJDIR_RELEASE)/src/entities/rectangle
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

